# Generated by Django 3.1 on 2020-08-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='detail',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
