# Generated by Django 3.1 on 2020-08-12 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0002_auto_20200812_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='login_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
